/*
 * Mistral AI API
 *
 * Our Chat Completion and Embeddings APIs specification. Create your account on [La Plateforme](https://console.mistral.ai) to get access and read the [docs](https://docs.mistral.ai) to learn how to use it.
 *
 * The version of the OpenAPI document: 0.0.2
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// FineTuneableModel : The name of the model to fine-tune.
/// The name of the model to fine-tune.
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum FineTuneableModel {
    #[serde(rename = "open-mistral-7b")]
    OpenMistral7b,
    #[serde(rename = "mistral-small-latest")]
    MistralSmallLatest,
    #[serde(rename = "codestral-latest")]
    CodestralLatest,
    #[serde(rename = "mistral-large-latest")]
    MistralLargeLatest,
    #[serde(rename = "open-mistral-nemo")]
    OpenMistralNemo,
    #[serde(rename = "ministral-3b-latest")]
    Ministral3bLatest,

}

impl std::fmt::Display for FineTuneableModel {
    fn fmt(&self, f: &mut std::fmt::Formatter) -> std::fmt::Result {
        match self {
            Self::OpenMistral7b => write!(f, "open-mistral-7b"),
            Self::MistralSmallLatest => write!(f, "mistral-small-latest"),
            Self::CodestralLatest => write!(f, "codestral-latest"),
            Self::MistralLargeLatest => write!(f, "mistral-large-latest"),
            Self::OpenMistralNemo => write!(f, "open-mistral-nemo"),
            Self::Ministral3bLatest => write!(f, "ministral-3b-latest"),
        }
    }
}

impl Default for FineTuneableModel {
    fn default() -> FineTuneableModel {
        Self::OpenMistral7b
    }
}

