/*
 * Mistral AI API
 *
 * Our Chat Completion and Embeddings APIs specification. Create your account on [La Plateforme](https://console.mistral.ai) to get access and read the [docs](https://docs.mistral.ai) to learn how to use it.
 *
 * The version of the OpenAPI document: 0.0.2
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// FunctionName : this restriction of `Function` is used to select a specific function to call
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct FunctionName {
    #[serde(rename = "name")]
    pub name: String,
}

impl FunctionName {
    /// this restriction of `Function` is used to select a specific function to call
    pub fn new(name: String) -> FunctionName {
        FunctionName {
            name,
        }
    }
}

