/*
 * Mistral AI API
 *
 * Our Chat Completion and Embeddings APIs specification. Create your account on [La Plateforme](https://console.mistral.ai) to get access and read the [docs](https://docs.mistral.ai) to learn how to use it.
 *
 * The version of the OpenAPI document: 0.0.2
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// ImageUrlChunk : {\"type\":\"image_url\",\"image_url\":{\"url\":\"data:image/png;base64,iVBORw0
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct ImageUrlChunk {
    #[serde(rename = "image_url")]
    pub image_url: Box<models::ImageUrl>,
    #[serde(rename = "type", skip_serializing_if = "Option::is_none")]
    pub r#type: Option<Type>,
}

impl ImageUrlChunk {
    /// {\"type\":\"image_url\",\"image_url\":{\"url\":\"data:image/png;base64,iVBORw0
    pub fn new(image_url: models::ImageUrl) -> ImageUrlChunk {
        ImageUrlChunk {
            image_url: Box::new(image_url),
            r#type: None,
        }
    }
}
/// 
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum Type {
    #[serde(rename = "image_url")]
    ImageUrl,
}

impl Default for Type {
    fn default() -> Type {
        Self::ImageUrl
    }
}

