/*
 * Mistral AI API
 *
 * Our Chat Completion and Embeddings APIs specification. Create your account on [La Plateforme](https://console.mistral.ai) to get access and read the [docs](https://docs.mistral.ai) to learn how to use it.
 *
 * The version of the OpenAPI document: 0.0.2
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// Input1 : Chat to classify
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct Input1 {
}

impl Input1 {
    /// Chat to classify
    pub fn new() -> Input1 {
        Input1 {
        }
    }
}

