/*
 * Mistral AI API
 *
 * Our Chat Completion and Embeddings APIs specification. Create your account on [La Plateforme](https://console.mistral.ai) to get access and read the [docs](https://docs.mistral.ai) to learn how to use it.
 *
 * The version of the OpenAPI document: 0.0.2
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
#[serde(tag = "type")]
pub enum JobOutIntegrationsInner {
    #[serde(rename="wandb")]
    Wandb(Box<models::WandbIntegrationOut>),
}

impl Default for JobOutIntegrationsInner {
    fn default() -> Self {
        Self::Wandb(Default::default())
    }
}


