/*
 * Mistral AI API
 *
 * Our Chat Completion and Embeddings APIs specification. Create your account on [La Plateforme](https://console.mistral.ai) to get access and read the [docs](https://docs.mistral.ai) to learn how to use it.
 *
 * The version of the OpenAPI document: 0.0.2
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct ListFilesOut {
    #[serde(rename = "data")]
    pub data: Vec<models::FileSchema>,
    #[serde(rename = "object")]
    pub object: String,
    #[serde(rename = "total")]
    pub total: i32,
}

impl ListFilesOut {
    pub fn new(data: Vec<models::FileSchema>, object: String, total: i32) -> ListFilesOut {
        ListFilesOut {
            data,
            object,
            total,
        }
    }
}

