/*
 * Mistral AI API
 *
 * Our Chat Completion and Embeddings APIs specification. Create your account on [La Plateforme](https://console.mistral.ai) to get access and read the [docs](https://docs.mistral.ai) to learn how to use it.
 *
 * The version of the OpenAPI document: 0.0.2
 *
 * Generated by: https://openapi-generator.tech
 */

use std::str::FromStr;

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct UserMessage {
    #[serde(rename = "content", deserialize_with = "Option::deserialize")]
    pub content: Option<Box<models::Content>>,
    #[serde(rename = "role", skip_serializing_if = "Option::is_none")]
    pub role: Option<Role>,
}

impl UserMessage {
    pub fn new(content: Option<models::Content>) -> UserMessage {
        UserMessage {
            content: if let Some(x) = content {
                Some(Box::new(x))
            } else {
                None
            },
            role: None,
        }
    }
}
///
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum Role {
    #[serde(rename = "user")]
    User,
}

impl Default for Role {
    fn default() -> Role {
        Self::User
    }
}

impl From<String> for UserMessage {
    fn from(s: String) -> Self {
        let content = models::Content::String(s);
        UserMessage::new(Some(content))
    }
}
